---
engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
ratings:
  paths:
  - "**.rb"
exclude_paths:
- ci/
- guides/
- tasks/
- tools/
